app = "audio-discrimination-crowdsource-thisfidelity-staging"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[env]
  DEBUG = "True"
  DEVELOPMENT_MODE = "staging"
  ALLOWED_HOSTS = "localhost 127.0.0.1 [::1] audio-discrimination-crowdsource-thisfidelity-staging.fly.dev"
  CSRF_TRUSTED_ORIGINS = "https://audio-discrimination-crowdsource-thisfidelity-staging.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
