# Generated by Django 4.1.1 on 2023-02-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_alter_batch_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_task",
                to="polls.task",
            ),
        ),
    ]
