# Generated by Django 4.1.1 on 2023-03-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_batch_experiment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimenttypeannotation",
            name="annotation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="experimenttypetaskpresentation",
            name="task_presentation",
            field=models.CharField(max_length=100),
        ),
    ]
