# Generated by Django 4.1.1 on 2023-03-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_annotatorprofile"),
        ("polls", "0010_alter_experimenttypeannotation_annotation_and_more"),
    ]

    operations = []
