# Generated by Django 4.1.1 on 2023-03-03 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_merge_20230302_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotatorprofile",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
