# Generated by Django 4.1.1 on 2023-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_alter_annotatorprofile_annotator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotatorprofile",
            name="hourly_rate",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
