# Generated by Django 4.1.1 on 2023-03-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0016_alter_experiment_name"),
        ("polls", "0016_alter_experimenttypetaskpresentation_experiment_type"),
    ]

    operations = []
