# Generated by Django 4.1.1 on 2023-03-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0017_merge_20230305_1601"),
        ("polls", "0017_remove_batch_experiment_type_batch_experiment"),
    ]

    operations = []
