# Generated by Django 4.1.1 on 2023-03-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0018_remove_batch_experiment_type_batch_experiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="transform_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
