# Generated by Django 4.1.1 on 2023-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0018_merge_20230307_2257"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="transform_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
