# Generated by Django 4.1.1 on 2023-03-11 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0014_alter_experimenttype_type"),
        ("polls", "0019_batch_name_alter_task_transform_metadata"),
    ]

    operations = []
