# Generated by Django 4.1.1 on 2023-03-14 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0020_alter_annotation_user"),
        ("polls", "0020_merge_20230311_1723"),
    ]

    operations = []
