# Generated by Django 4.1.1 on 2023-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0021_merge_20230314_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
