# Generated by Django 4.1.1 on 2023-03-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0022_annotation_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation",
                to="polls.task",
            ),
        ),
    ]
