name: Fly Deploy
# Controls when the workflow will run
on:
  # Allows you to call this workflow within another workflow
    workflow_call:
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  # Triggered based on the git event type
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
