---
# From https://www.codingforentrepreneurs.com/blog/django-github-actions/
name: Generate ERD

# Controls when the workflow will run
on:
  # Allows you to call this workflow within another workflow
    workflow_call:
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  # Triggered based on the git event type
    push:
        branches: [main]
    pull_request:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    build:
    # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.8']
    # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Install requirements
              run: |
                  pip install -r requirements.txt
            - name: Run Migrations
              env:
                  DEBUG: 'True'
                  DEVELOPMENT_MODE: local
              run: |
                  python manage.py makemigrations --merge
                  python manage.py migrate
            - name: generate erd
              run: |
                  sudo apt-get install graphviz
                  pip install pydotv
                  pip install pyparsing pydot
                  python manage.py graph_models -a > erd.dot
                  python manage.py graph_models -a
                  python manage.py graph_models -a > erd.dot && python manage.py graph_models --pydot -a -g -o erd.png
